# Generated by Django 4.2.18 on 2025-03-31 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('waiting_period', models.IntegerField(null=True)),
            ],
        ),
    ]
